services:
  master-danieeeld2:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H https://192.168.10.50:443/
    networks:
      p5-granjaweb_red_web:
        ipv4_address: 192.168.10.70

  worker-danieeeld2:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host=master-danieeeld2
    depends_on:
      - master-danieeeld2
    deploy:
      replicas: 5
    networks:
      p5-granjaweb_red_web:

networks:
  p5-granjaweb_red_web:
    external: true